document.write("<p>Version: ");
document.write(navegador.ver);
document.write("</p>");
document.write("<p>Plataforma: ");
document.write(navegador.plataforma);
document.write("</p>");
document.write("<p>Vendedor: ");
document.write(navegador.vendor);
document.write("</p>");
document.write("<p>Agente: ");
document.write(navegador.agenteUsuario);
document.write("</p>");
document.write("<p>Java: ");
document.write(navegador.java);
document.write("</p>");